package com.saamaka.dico.testeurs

data class AppStrings(
    val speaker: String,
    val guest: String,
    val freeAccount: String,
    val translate: String,
    val premium: String,
    val tester: String,
    val notSpecified: String,
    val dictionaryTitle: String,
    val back: String,
    val language: String,
    val enterTesterNameFirst: String,
    val wordsAvailable: String,
    val officiallyValidated: String,
    val toReview: String,
    val waiting: String,
    val searchPlaceholder: String,
    val startSearching: String,
    val noResult: String,
    val results: String,
    val verified: String,
    val wordCopied: String,
    val shareChooser: String,
    val testerSpeakerName: String,
    val continueText: String,
    val quit: String,
    val instructionSearch: String,
    val instructionValidate: String,
    val instructionCorrect: String,
    val instructionExport: String,

    // Navigation
    val search: String,
    val mission: String,
    val favorites: String,
    val history: String,
    val corrections: String,

    // Sélecteur de langue
    val interfaceLanguage: String,
    val saamaka: String,
    val french: String,
    val english: String,
    val dutch: String,
    val proposeCorrection: String,
    val wordDetails: String,
    val appTitle: String,
    val pronunciationSaamaka: String,
    val recordPronunciation: String,
    val stopAndSave: String,
    val listen: String,
    val deleteRedo: String,
    val nextWord: String,
    val removeFavorite: String,
    val addFavorite: String,
    val copy: String,
    val share: String,
    val linguisticValidation: String,
    val validationExplanation: String,
    val validatedO: String,
    val validateO: String,
    val correct: String,
    val correctorName: String,
    val proposedFrench: String,
    val proposedSaamaka: String,
    val commentExplanation: String,
    val saveCorrection: String,
    val correctionSaved: String,
    val cancel: String
)

fun stringsFor(language: UiLanguage): AppStrings {
    return when (language) {

        UiLanguage.SAAMAKA -> AppStrings(
            dictionaryTitle = "Saamaka Woordenboek",
            speaker = "Takiman",
            guest = "Invité",
            freeAccount = "Compte gratuit",
            premium = "Premium",
            tester = "Testiman",
            wordCopied = "Wootu kopi",
            correctionSaved = "Koreksi kibri",
            notSpecified = "no taki",
            language = "Tongo",
            enterTesterNameFirst = "Putu fosi a nen fu a testiman",
            testerSpeakerName = "Nen fu testiman / takiman",
            continueText = "Go doo",
            quit = "Komoto",
            translate = "Traaduuku",
            shareChooser = "Deli",
            wordsAvailable = "wootu de",
            officiallyValidated = "wootu di a valide",
            toReview = "fu luku ete",
            waiting = "de wakti",
            searchPlaceholder = "Suku wan wootu",
            startSearching = "Bigi ta sikifi fu suku",
            noResult = "No feni noti",
            results = "feni",
            verified = "Valide",
            back = "← Baka",

            search = "Suku",
            mission = "Wooko",
            favorites = "Lobi",
            history = "Fosi suku",
            corrections = "Koreksi",

            interfaceLanguage = "Tongo fu a app",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",


            proposeCorrection = "Koreksi",
            wordDetails = "Wootu info",
            pronunciationSaamaka = "Saamaka taki",
            appTitle = "Saamaka Dico Testeurs",
            recordPronunciation = "🎙 Teki a taki",
            stopAndSave = "⏹ Stop nanga kibri",
            listen = "▶ Taki",
            deleteRedo = "🗑 Puru / du baka",
            nextWord = "Go na a tra wootu",
            // SAAMAKA — provisoire à valider
            removeFavorite = "Puru na lobi",
            addFavorite = "Putu na lobi",
            copy = "Kopi",
            share = "Deli",
            linguisticValidation = "Tongo validasi",
            validationExplanation = "Te yu valide, a vertaling sa kisi O na a baka versi.",
            validatedO = "✓ Valide O",
            validateO = "✓ Valide O",
            correct = "✏ Koreksi",
            correctorName = "Nen fu korekturu",
            proposedFrench = "Français di yu wani",
            proposedSaamaka = "Saamaka di yu wani",
            commentExplanation = "Komentari / ferklaringi",
            saveCorrection = "Kibri a koreksi",
            cancel = "Kansel",
            instructionSearch = "1. Suku of waka na ini den wootu.",
            instructionValidate = "2. Valide O te wan traaduuku de bun.",
            instructionCorrect = "3. Koreksi te wan traaduuku no de bun.",
            instructionExport = "4. Export den validasi anga koreksi fu ten na ten.",
        )

        UiLanguage.FRENCH -> AppStrings(
            dictionaryTitle = "Dictionnaire Saamaka",
            language = "Langue",
            guest = "Invité",
            freeAccount = "Compte gratuit",
            premium = "Premium",
            tester = "Testeur",
            speaker = "Locuteur",
            shareChooser = "Partager",
            correctionSaved = "Correction enregistrée",
            notSpecified = "non renseigné",
            wordsAvailable = "mots disponibles",
            officiallyValidated = "validés officiellement",
            toReview = "à vérifier",
            waiting = "en attente",
            searchPlaceholder = "Rechercher un mot",
            startSearching = "Commence à écrire pour rechercher",
            noResult = "Aucun résultat trouvé",
            translate = "Traduire",
            results = "résultat(s)",
            verified = "Vérifié",
            enterTesterNameFirst = "Indiquez d'abord le nom du testeur",
            back = "← Retour",
            wordCopied = "Mot copié",

            search = "Recherche",
            pronunciationSaamaka = "Prononciation Saamaka",
            mission = "Mission",
            favorites = "Favoris",
            history = "Historique",
            corrections = "Corrections",

            interfaceLanguage = "Langue de l'application",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",

            proposeCorrection = "Proposer une correction",
            wordDetails = "Fiche du mot",
            appTitle = "Saamaka Dico Testeurs",
            recordPronunciation = "🎙 Enregistrer la prononciation",
            stopAndSave = "⏹ Arrêter et enregistrer",
            listen = "▶ Prononcer",
            deleteRedo = "🗑 Supprimer / Refaire",
            nextWord = "Passer au mot suivant",
            removeFavorite = "Retirer des favoris",
            addFavorite = "Ajouter aux favoris",
            copy = "Copier",
            share = "Partager",
            linguisticValidation = "Validation linguistique",
            validationExplanation = "Valider signifie que cette traduction pourra passer à O dans la prochaine version.",
            validatedO = "✓ Validé O",
            validateO = "✓ Valider O",
            correct = "✏ Corriger",
            correctorName = "Nom du correcteur",
            proposedFrench = "Français proposé",
            proposedSaamaka = "Saamaka proposé",
            commentExplanation = "Commentaire / explication",
            saveCorrection = "Enregistrer la correction",
            testerSpeakerName = "Nom du testeur / locuteur",
            continueText = "Continuer",
            quit = "Quitter",
            cancel = "Annuler",
            instructionSearch = "1. Rechercher ou parcourir librement les mots.",
            instructionValidate = "2. Valider O lorsqu'une traduction est correcte.",
            instructionCorrect = "3. Corriger lorsqu'une traduction est incorrecte.",
            instructionExport = "4. Exporter les validations et corrections régulièrement.",
        )


        UiLanguage.ENGLISH -> AppStrings(
            dictionaryTitle = "Saamaka Dictionary",
            language = "Language",
            wordsAvailable = "words available",
            officiallyValidated = "officially validated",
            toReview = "to review",
            waiting = "pending",
            guest = "Guest",
            freeAccount = "Free account",
            premium = "Premium",
            tester = "Tester",
            translate = "Translate",
            wordCopied = "Word copied",
            testerSpeakerName = "Tester / speaker name",
            continueText = "Continue",
            quit = "Exit",
            correctionSaved = "Correction saved",
            searchPlaceholder = "Search for a word",
            startSearching = "Start typing to search",
            noResult = "No results found",
            results = "result(s)",
            speaker = "Speaker",
            notSpecified = "not specified",
            verified = "Verified",
            enterTesterNameFirst = "Enter the tester name first",
            shareChooser = "Share",
            back = "← Back",
            pronunciationSaamaka = "Saamaka pronunciation",

            search = "Search",
            mission = "Mission",
            favorites = "Favorites",
            history = "History",
            corrections = "Corrections",

            interfaceLanguage = "App language",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",

            proposeCorrection = "Suggest a correction",
            wordDetails = "Word details",
            appTitle = "Saamaka Dico Testers",
            recordPronunciation = "🎙 Record pronunciation",
            stopAndSave = "⏹ Stop and save",
            listen = "▶ Pronounce",
            deleteRedo = "🗑 Delete / Record again",
            nextWord = "Go to next word",
            // ENGLISH
            removeFavorite = "Remove from favorites",
            addFavorite = "Add to favorites",
            copy = "Copy",
            share = "Share",
            linguisticValidation = "Linguistic validation",
            validationExplanation = "Validating means this translation can be marked O in the next version.",
            validatedO = "✓ Validated O",
            validateO = "✓ Validate O",
            correct = "✏ Correct",
            correctorName = "Corrector name",
            proposedFrench = "Proposed French",
            proposedSaamaka = "Proposed Saamaka",
            commentExplanation = "Comment / explanation",
            saveCorrection = "Save correction",
            cancel = "Cancel",
            instructionSearch = "1. Search or freely browse the words.",
            instructionValidate = "2. Validate O when a translation is correct.",
            instructionCorrect = "3. Correct a translation when it is incorrect.",
            instructionExport = "4. Export validations and corrections regularly.",
        )


        UiLanguage.DUTCH -> AppStrings(
            dictionaryTitle = "Saamaka Woordenboek",
            language = "Taal",
            correctionSaved = "Correctie opgeslagen",
            wordsAvailable = "woorden beschikbaar",
            wordCopied = "Woord gekopieerd",guest = "Gast",
            freeAccount = "Gratis account",
            premium = "Premium",
            tester = "Tester",
            officiallyValidated = "officieel gevalideerd",
            testerSpeakerName = "Naam van tester / spreker",
            continueText = "Doorgaan",
            quit = "Afsluiten",
            toReview = "te controleren",
            translate = "Vertalen",
            waiting = "in afwachting",
            speaker = "Spreker",
            shareChooser = "Delen",
            enterTesterNameFirst = "Vul eerst de naam van de tester in",
            notSpecified = "niet opgegeven",
            back = "← Terug",
            searchPlaceholder = "Zoek een woord",
            startSearching = "Begin te typen om te zoeken",
            noResult = "Geen resultaten gevonden",
            results = "resultaat/resultaten",
            pronunciationSaamaka = "Saamaka uitspraak",
            verified = "Gecontroleerd",

            search = "Zoeken",
            mission = "Missie",
            favorites = "Favorieten",
            history = "Geschiedenis",
            corrections = "Correcties",

            interfaceLanguage = "Taal van de app",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",

            proposeCorrection = "Correctie voorstellen",
            wordDetails = "Woordfiche",
            appTitle = "Saamaka Dico Testers",
            recordPronunciation = "🎙 Uitspraak opnemen",
            stopAndSave = "⏹ Stoppen en opslaan",
            listen = "▶ Uitspreken",
            deleteRedo = "🗑 Verwijderen / Opnieuw opnemen",
            nextWord = "Ga naar het volgende woord",
            // DUTCH
            removeFavorite = "Uit favorieten verwijderen",
            addFavorite = "Aan favorieten toevoegen",
            copy = "Kopiëren",
            share = "Delen",
            linguisticValidation = "Taalkundige validatie",
            validationExplanation = "Na validatie kan deze vertaling in de volgende versie als O worden gemarkeerd.",
            validatedO = "✓ Gevalideerd O",
            validateO = "✓ Valideren O",
            correct = "✏ Corrigeren",
            correctorName = "Naam van de corrector",
            proposedFrench = "Voorgesteld Frans",
            proposedSaamaka = "Voorgesteld Saamaka",
            commentExplanation = "Opmerking / uitleg",
            saveCorrection = "Correctie opslaan",
            cancel = "Annuleren",
            instructionSearch = "1. Zoek of blader vrij door de woorden.",
            instructionValidate = "2. Valideer O wanneer een vertaling correct is.",
            instructionCorrect = "3. Corrigeer een vertaling wanneer deze onjuist is.",
            instructionExport = "4. Exporteer regelmatig de validaties en correcties.",
        )

    }
}

fun stringsFor(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.FRENCH -> stringsFor(UiLanguage.FRENCH)
        AppLanguage.ENGLISH -> stringsFor(UiLanguage.ENGLISH)
        AppLanguage.DUTCH -> stringsFor(UiLanguage.DUTCH)
    }
}