package com.saamaka.dico.testeurs

data class AppStrings(
    val speaker: String,
    val guest: String,
    val freeAccount: String,
    val translate: String,
    val premium: String,
    val tester: String,
    val notSpecified: String,
    val dictionaryTitle: String,
    val back: String,
    val language: String,
    val enterTesterNameFirst: String,
    val wordsAvailable: String,
    val officiallyValidated: String,
    val toReview: String,
    val waiting: String,
    val searchPlaceholder: String,
    val startSearching: String,
    val noResult: String,
    val results: String,
    val verified: String,
    val wordCopied: String,
    val shareChooser: String,
    val testerSpeakerName: String,
    val continueText: String,
    val quit: String,
    val instructionSearch: String,
    val instructionValidate: String,
    val instructionCorrect: String,
    val instructionExport: String,

    // Navigation
    val search: String,
    val mission: String,
    val favorites: String,
    val history: String,
    val corrections: String,

    // Sélecteur de langue
    val interfaceLanguage: String,
    val saamaka: String,
    val french: String,
    val english: String,
    val dutch: String,
    val proposeCorrection: String,
    val wordDetails: String,
    val appTitle: String,
    val pronunciationSaamaka: String,
    val recordPronunciation: String,
    val stopAndSave: String,
    val listen: String,
    val deleteRedo: String,
    val nextWord: String,
    val removeFavorite: String,
    val addFavorite: String,
    val copy: String,
    val share: String,
    val linguisticValidation: String,
    val validationExplanation: String,
    val validatedO: String,
    val validateO: String,
    val correct: String,
    val correctorName: String,
    val proposedFrench: String,
    val proposedSaamaka: String,
    val commentExplanation: String,
    val saveCorrection: String,
    val correctionSaved: String,
    val cancel: String,
    val reportDeletion: String,
    val deletionProposed: String,
    val cancelDeletionProposal: String,
    val deletionReasonTitle: String,
    val deletionOtherExplanation: String,
    val deletionConfirmation: String,
    val confirm: String,
    val deletionReasons: List<String>,
    val proposedDeletionsSection: String,
    val proposedDeletionsCount: String,
    val deletionReasonLabel: String,
    val deletionCommentLabel: String,
    val deletionTesterLabel: String,
    val deletionDateLabel: String,
    val openEntry: String,
    val cancelDeletionConfirmation: String,
    val noProposedDeletion: String,
    val proposeNewEntry: String,
    val proposedNewEntries: String,
    val newEntriesCount: String,
    val category: String,
    val optionalComment: String,
    val saveProposal: String,
    val editProposal: String,
    val cancelProposal: String,
    val cancelNewEntryConfirmation: String,
    val atLeastOneTranslation: String,
    val duplicateEntryWarning: String,
    val noProposedNewEntry: String,
    val recordProposalAudio: String,
    val stopProposalAudio: String,
    val proposalAudioRecorded: String,
    val saamakaRequired: String,
    val stopListening: String
)

fun stringsFor(language: UiLanguage): AppStrings {
    return when (language) {

        UiLanguage.SAAMAKA -> AppStrings(
            dictionaryTitle = "Saamaka Woordenboek",
            speaker = "Takiman",
            guest = "Invité",
            freeAccount = "Compte gratuit",
            premium = "Premium",
            tester = "Testiman",
            wordCopied = "Wootu kopi",
            correctionSaved = "Koreksi kibri",
            notSpecified = "no taki",
            language = "Tongo",
            enterTesterNameFirst = "Putu fosi a nen fu a testiman",
            testerSpeakerName = "Nen fu testiman / takiman",
            continueText = "Go doo",
            quit = "Komoto",
            translate = "Traaduuku",
            shareChooser = "Deli",
            wordsAvailable = "wootu de",
            officiallyValidated = "wootu di a valide",
            toReview = "fu luku ete",
            waiting = "de wakti",
            searchPlaceholder = "Suku wan wootu",
            startSearching = "Bigi ta sikifi fu suku",
            noResult = "No feni noti",
            results = "feni",
            verified = "Valide",
            back = "← Baka",

            search = "Suku",
            mission = "Wooko",
            favorites = "Lobi",
            history = "Fosi suku",
            corrections = "Koreksi",

            interfaceLanguage = "Tongo fu a app",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",


            proposeCorrection = "Koreksi",
            wordDetails = "Wootu info",
            pronunciationSaamaka = "Saamaka taki",
            appTitle = "Saamaka Dico Testeurs",
            recordPronunciation = "🎙 Teki a taki",
            stopAndSave = "⏹ Stop nanga kibri",
            listen = "▶ Taki",
            deleteRedo = "🗑 Puru / du baka",
            nextWord = "Go na a tra wootu",
            // SAAMAKA — provisoire à valider
            removeFavorite = "Puru na lobi",
            addFavorite = "Putu na lobi",
            copy = "Kopi",
            share = "Deli",
            linguisticValidation = "Tongo validasi",
            validationExplanation = "Te yu valide, a vertaling sa kisi O na a baka versi.",
            validatedO = "✓ Valide O",
            validateO = "✓ Valide O",
            correct = "✏ Koreksi",
            correctorName = "Nen fu korekturu",
            proposedFrench = "Français di yu wani",
            proposedSaamaka = "Saamaka di yu wani",
            commentExplanation = "Komentari / ferklaringi",
            saveCorrection = "Kibri a koreksi",
            cancel = "Kansel",
            reportDeletion = "Meki wan taki fu puru",
            deletionProposed = "A taki de fu puru",
            cancelDeletionProposal = "Kansel a taki fu puru",
            deletionReasonTitle = "Fa a musu puru?",
            deletionOtherExplanation = "Sikifi fa a musu puru",
            deletionConfirmation = "Yu wani kibri a taki fu puru disi? A wootu no sa puru na a diko.",
            confirm = "Kibri",
            deletionReasons = listOf(
                "A taki no man de of no man ferstan",
                "A de tu ten",
                "Wootu of traaduuku no bun",
                "A taki tu langa",
                "A no de Saamaka",
                "Wan tra fasi"
            ),
            proposedDeletionsSection = "Den taki fu puru",
            proposedDeletionsCount = "taki fu puru",
            deletionReasonLabel = "Fa",
            deletionCommentLabel = "Komentari",
            deletionTesterLabel = "Testiman",
            deletionDateLabel = "Dei",
            openEntry = "Luku a wootu",
            cancelDeletionConfirmation = "Yu wani kansel a taki fu puru disi?",
            noProposedDeletion = "No wan taki fu puru de.",
            proposeNewEntry = "Meki wan nyun wootu",
            proposedNewEntries = "Den nyun wootu di a taki",
            newEntriesCount = "nyun wootu",
            category = "Grupu",
            optionalComment = "Komentari (no musu)",
            saveProposal = "Kibri a taki",
            editProposal = "Kenki",
            cancelProposal = "Kansel a taki",
            cancelNewEntryConfirmation = "Yu wani kansel a nyun wootu disi?",
            atLeastOneTranslation = "Putu wan traaduuku moro nanga Saamaka.",
            duplicateEntryWarning = "A wootu de kaba.",
            noProposedNewEntry = "No wan nyun wootu de.",
            recordProposalAudio = "Teki a Saamaka taki",
            stopProposalAudio = "Stop nanga kibri",
            proposalAudioRecorded = "A taki kibri",
            saamakaRequired = "Saamaka musu de.",
            stopListening = "Stop a taki",
            instructionSearch = "1. Suku of waka na ini den wootu.",
            instructionValidate = "2. Valide O te wan traaduuku de bun.",
            instructionCorrect = "3. Koreksi te wan traaduuku no de bun.",
            instructionExport = "4. Export den validasi anga koreksi fu ten na ten.",
        )

        UiLanguage.FRENCH -> AppStrings(
            dictionaryTitle = "Dictionnaire Saamaka",
            language = "Langue",
            guest = "Invité",
            freeAccount = "Compte gratuit",
            premium = "Premium",
            tester = "Testeur",
            speaker = "Locuteur",
            shareChooser = "Partager",
            correctionSaved = "Correction enregistrée",
            notSpecified = "non renseigné",
            wordsAvailable = "mots disponibles",
            officiallyValidated = "validés officiellement",
            toReview = "à vérifier",
            waiting = "en attente",
            searchPlaceholder = "Rechercher un mot",
            startSearching = "Commence à écrire pour rechercher",
            noResult = "Aucun résultat trouvé",
            translate = "Traduire",
            results = "résultat(s)",
            verified = "Vérifié",
            enterTesterNameFirst = "Indiquez d'abord le nom du testeur",
            back = "← Retour",
            wordCopied = "Mot copié",

            search = "Recherche",
            pronunciationSaamaka = "Prononciation Saamaka",
            mission = "Mission",
            favorites = "Favoris",
            history = "Historique",
            corrections = "Corrections",

            interfaceLanguage = "Langue de l'application",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",

            proposeCorrection = "Proposer une correction",
            wordDetails = "Fiche du mot",
            appTitle = "Saamaka Dico Testeurs",
            recordPronunciation = "🎙 Enregistrer la prononciation",
            stopAndSave = "⏹ Arrêter et enregistrer",
            listen = "▶ Prononcer",
            deleteRedo = "🗑 Supprimer / Refaire",
            nextWord = "Passer au mot suivant",
            removeFavorite = "Retirer des favoris",
            addFavorite = "Ajouter aux favoris",
            copy = "Copier",
            share = "Partager",
            linguisticValidation = "Validation linguistique",
            validationExplanation = "Valider signifie que cette traduction pourra passer à O dans la prochaine version.",
            validatedO = "✓ Validé O",
            validateO = "✓ Valider O",
            correct = "✏ Corriger",
            correctorName = "Nom du correcteur",
            proposedFrench = "Français proposé",
            proposedSaamaka = "Saamaka proposé",
            commentExplanation = "Commentaire / explication",
            saveCorrection = "Enregistrer la correction",
            testerSpeakerName = "Nom du testeur / locuteur",
            continueText = "Continuer",
            quit = "Quitter",
            cancel = "Annuler",
            reportDeletion = "Signaler pour suppression",
            deletionProposed = "Suppression proposée",
            cancelDeletionProposal = "Annuler le signalement",
            deletionReasonTitle = "Motif du signalement",
            deletionOtherExplanation = "Explication obligatoire",
            deletionConfirmation = "Confirmer cette proposition de suppression ? L'entrée restera dans le dictionnaire.",
            confirm = "Confirmer",
            deletionReasons = listOf(
                "Expression impossible ou incompréhensible",
                "Doublon",
                "Mot ou traduction incorrecte",
                "Expression trop longue",
                "Ne correspond pas au saamaka",
                "Autre motif"
            ),
            proposedDeletionsSection = "Suppressions proposées",
            proposedDeletionsCount = "proposition(s) de suppression",
            deletionReasonLabel = "Motif",
            deletionCommentLabel = "Commentaire",
            deletionTesterLabel = "Testeur",
            deletionDateLabel = "Date",
            openEntry = "Ouvrir la fiche",
            cancelDeletionConfirmation = "Confirmer l'annulation de votre proposition de suppression ?",
            noProposedDeletion = "Aucune suppression proposée.",
            proposeNewEntry = "Proposer une nouvelle entrée",
            proposedNewEntries = "Nouvelles entrées proposées",
            newEntriesCount = "nouvelle(s) entrée(s)",
            category = "Catégorie",
            optionalComment = "Commentaire facultatif",
            saveProposal = "Enregistrer la proposition",
            editProposal = "Modifier",
            cancelProposal = "Annuler la proposition",
            cancelNewEntryConfirmation = "Confirmer l'annulation de votre nouvelle entrée proposée ?",
            atLeastOneTranslation = "Renseignez au moins une traduction en plus du saamaka.",
            duplicateEntryWarning = "Cette entrée existe déjà dans le dictionnaire ou les propositions.",
            noProposedNewEntry = "Aucune nouvelle entrée proposée.",
            recordProposalAudio = "Enregistrer la prononciation",
            stopProposalAudio = "Arrêter et enregistrer",
            proposalAudioRecorded = "Prononciation enregistrée",
            saamakaRequired = "Le saamaka est obligatoire.",
            stopListening = "Arrêter la lecture",
            instructionSearch = "1. Rechercher ou parcourir librement les mots.",
            instructionValidate = "2. Valider O lorsqu'une traduction est correcte.",
            instructionCorrect = "3. Corriger lorsqu'une traduction est incorrecte.",
            instructionExport = "4. Exporter les validations et corrections régulièrement.",
        )


        UiLanguage.ENGLISH -> AppStrings(
            dictionaryTitle = "Saamaka Dictionary",
            language = "Language",
            wordsAvailable = "words available",
            officiallyValidated = "officially validated",
            toReview = "to review",
            waiting = "pending",
            guest = "Guest",
            freeAccount = "Free account",
            premium = "Premium",
            tester = "Tester",
            translate = "Translate",
            wordCopied = "Word copied",
            testerSpeakerName = "Tester / speaker name",
            continueText = "Continue",
            quit = "Exit",
            correctionSaved = "Correction saved",
            searchPlaceholder = "Search for a word",
            startSearching = "Start typing to search",
            noResult = "No results found",
            results = "result(s)",
            speaker = "Speaker",
            notSpecified = "not specified",
            verified = "Verified",
            enterTesterNameFirst = "Enter the tester name first",
            shareChooser = "Share",
            back = "← Back",
            pronunciationSaamaka = "Saamaka pronunciation",

            search = "Search",
            mission = "Mission",
            favorites = "Favorites",
            history = "History",
            corrections = "Corrections",

            interfaceLanguage = "App language",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",

            proposeCorrection = "Suggest a correction",
            wordDetails = "Word details",
            appTitle = "Saamaka Dico Testers",
            recordPronunciation = "🎙 Record pronunciation",
            stopAndSave = "⏹ Stop and save",
            listen = "▶ Pronounce",
            deleteRedo = "🗑 Delete / Record again",
            nextWord = "Go to next word",
            // ENGLISH
            removeFavorite = "Remove from favorites",
            addFavorite = "Add to favorites",
            copy = "Copy",
            share = "Share",
            linguisticValidation = "Linguistic validation",
            validationExplanation = "Validating means this translation can be marked O in the next version.",
            validatedO = "✓ Validated O",
            validateO = "✓ Validate O",
            correct = "✏ Correct",
            correctorName = "Corrector name",
            proposedFrench = "Proposed French",
            proposedSaamaka = "Proposed Saamaka",
            commentExplanation = "Comment / explanation",
            saveCorrection = "Save correction",
            cancel = "Cancel",
            reportDeletion = "Report for deletion",
            deletionProposed = "Deletion proposed",
            cancelDeletionProposal = "Cancel deletion report",
            deletionReasonTitle = "Reason for reporting",
            deletionOtherExplanation = "Required explanation",
            deletionConfirmation = "Confirm this deletion proposal? The entry will remain in the dictionary.",
            confirm = "Confirm",
            deletionReasons = listOf(
                "Impossible or incomprehensible expression",
                "Duplicate",
                "Incorrect word or translation",
                "Expression is too long",
                "Does not correspond to Saamaka",
                "Other reason"
            ),
            proposedDeletionsSection = "Proposed deletions",
            proposedDeletionsCount = "deletion proposal(s)",
            deletionReasonLabel = "Reason",
            deletionCommentLabel = "Comment",
            deletionTesterLabel = "Tester",
            deletionDateLabel = "Date",
            openEntry = "Open entry",
            cancelDeletionConfirmation = "Confirm cancellation of your deletion proposal?",
            noProposedDeletion = "No proposed deletions.",
            proposeNewEntry = "Propose a new entry",
            proposedNewEntries = "Proposed new entries",
            newEntriesCount = "new entry proposal(s)",
            category = "Category",
            optionalComment = "Optional comment",
            saveProposal = "Save proposal",
            editProposal = "Edit",
            cancelProposal = "Cancel proposal",
            cancelNewEntryConfirmation = "Confirm cancellation of your proposed new entry?",
            atLeastOneTranslation = "Enter at least one translation in addition to Saamaka.",
            duplicateEntryWarning = "This entry already exists in the dictionary or proposals.",
            noProposedNewEntry = "No proposed new entries.",
            recordProposalAudio = "Record pronunciation",
            stopProposalAudio = "Stop and save",
            proposalAudioRecorded = "Pronunciation recorded",
            saamakaRequired = "Saamaka is required.",
            stopListening = "Stop playback",
            instructionSearch = "1. Search or freely browse the words.",
            instructionValidate = "2. Validate O when a translation is correct.",
            instructionCorrect = "3. Correct a translation when it is incorrect.",
            instructionExport = "4. Export validations and corrections regularly.",
        )


        UiLanguage.DUTCH -> AppStrings(
            dictionaryTitle = "Saamaka Woordenboek",
            language = "Taal",
            correctionSaved = "Correctie opgeslagen",
            wordsAvailable = "woorden beschikbaar",
            wordCopied = "Woord gekopieerd",guest = "Gast",
            freeAccount = "Gratis account",
            premium = "Premium",
            tester = "Tester",
            officiallyValidated = "officieel gevalideerd",
            testerSpeakerName = "Naam van tester / spreker",
            continueText = "Doorgaan",
            quit = "Afsluiten",
            toReview = "te controleren",
            translate = "Vertalen",
            waiting = "in afwachting",
            speaker = "Spreker",
            shareChooser = "Delen",
            enterTesterNameFirst = "Vul eerst de naam van de tester in",
            notSpecified = "niet opgegeven",
            back = "← Terug",
            searchPlaceholder = "Zoek een woord",
            startSearching = "Begin te typen om te zoeken",
            noResult = "Geen resultaten gevonden",
            results = "resultaat/resultaten",
            pronunciationSaamaka = "Saamaka uitspraak",
            verified = "Gecontroleerd",

            search = "Zoeken",
            mission = "Missie",
            favorites = "Favorieten",
            history = "Geschiedenis",
            corrections = "Correcties",

            interfaceLanguage = "Taal van de app",
            saamaka = "Saamaka",
            french = "Français",
            english = "English",
            dutch = "Nederlands",

            proposeCorrection = "Correctie voorstellen",
            wordDetails = "Woordfiche",
            appTitle = "Saamaka Dico Testers",
            recordPronunciation = "🎙 Uitspraak opnemen",
            stopAndSave = "⏹ Stoppen en opslaan",
            listen = "▶ Uitspreken",
            deleteRedo = "🗑 Verwijderen / Opnieuw opnemen",
            nextWord = "Ga naar het volgende woord",
            // DUTCH
            removeFavorite = "Uit favorieten verwijderen",
            addFavorite = "Aan favorieten toevoegen",
            copy = "Kopiëren",
            share = "Delen",
            linguisticValidation = "Taalkundige validatie",
            validationExplanation = "Na validatie kan deze vertaling in de volgende versie als O worden gemarkeerd.",
            validatedO = "✓ Gevalideerd O",
            validateO = "✓ Valideren O",
            correct = "✏ Corrigeren",
            correctorName = "Naam van de corrector",
            proposedFrench = "Voorgesteld Frans",
            proposedSaamaka = "Voorgesteld Saamaka",
            commentExplanation = "Opmerking / uitleg",
            saveCorrection = "Correctie opslaan",
            cancel = "Annuleren",
            reportDeletion = "Melden voor verwijdering",
            deletionProposed = "Verwijdering voorgesteld",
            cancelDeletionProposal = "Melding annuleren",
            deletionReasonTitle = "Reden van de melding",
            deletionOtherExplanation = "Verplichte uitleg",
            deletionConfirmation = "Dit verwijderingsvoorstel bevestigen? De vermelding blijft in het woordenboek.",
            confirm = "Bevestigen",
            deletionReasons = listOf(
                "Onmogelijke of onbegrijpelijke uitdrukking",
                "Duplicaat",
                "Onjuist woord of onjuiste vertaling",
                "Uitdrukking is te lang",
                "Komt niet overeen met Saamaka",
                "Andere reden"
            ),
            proposedDeletionsSection = "Voorgestelde verwijderingen",
            proposedDeletionsCount = "verwijderingsvoorstel(len)",
            deletionReasonLabel = "Reden",
            deletionCommentLabel = "Opmerking",
            deletionTesterLabel = "Tester",
            deletionDateLabel = "Datum",
            openEntry = "Vermelding openen",
            cancelDeletionConfirmation = "Annulering van uw verwijderingsvoorstel bevestigen?",
            noProposedDeletion = "Geen voorgestelde verwijderingen.",
            proposeNewEntry = "Nieuwe vermelding voorstellen",
            proposedNewEntries = "Voorgestelde nieuwe vermeldingen",
            newEntriesCount = "voorstel(len) voor nieuwe vermeldingen",
            category = "Categorie",
            optionalComment = "Optionele opmerking",
            saveProposal = "Voorstel opslaan",
            editProposal = "Bewerken",
            cancelProposal = "Voorstel annuleren",
            cancelNewEntryConfirmation = "Annulering van uw voorgestelde nieuwe vermelding bevestigen?",
            atLeastOneTranslation = "Voer naast Saamaka minstens één vertaling in.",
            duplicateEntryWarning = "Deze vermelding bestaat al in het woordenboek of de voorstellen.",
            noProposedNewEntry = "Geen voorgestelde nieuwe vermeldingen.",
            recordProposalAudio = "Uitspraak opnemen",
            stopProposalAudio = "Stoppen en opslaan",
            proposalAudioRecorded = "Uitspraak opgenomen",
            saamakaRequired = "Saamaka is verplicht.",
            stopListening = "Afspelen stoppen",
            instructionSearch = "1. Zoek of blader vrij door de woorden.",
            instructionValidate = "2. Valideer O wanneer een vertaling correct is.",
            instructionCorrect = "3. Corrigeer een vertaling wanneer deze onjuist is.",
            instructionExport = "4. Exporteer regelmatig de validaties en correcties.",
        )

    }
}

fun stringsFor(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.FRENCH -> stringsFor(UiLanguage.FRENCH)
        AppLanguage.ENGLISH -> stringsFor(UiLanguage.ENGLISH)
        AppLanguage.DUTCH -> stringsFor(UiLanguage.DUTCH)
        AppLanguage.SAAMAKA -> stringsFor(UiLanguage.SAAMAKA)
    }
}
